### ISSUE TITLE
首次进入loading的时间问题

### ISSUE THREAD

**Issue by PineSongCN** [vueComponent/ant-design-vue-pro#611]
**Question （问题描述）**
首次进入页面大约有5秒作用的空白，没有请求网络，请问这段时间是在做什么处理？是否能够去除？前后加起来大概十秒才会停止loading出现页面
![image](https://user-images.githubusercontent.com/39976617/71659224-c48fa200-2d81-11ea-8230-2d1485ae4793.png)

**Describe the solution you'd like （你期待的是什么？）**
减少加载时间

**Comment by sendya** [comment]
https://preview.pro.loacg.com/  没你说的问题，什么环境？

**Comment by PineSongCN** [comment]
> https://preview.pro.loacg.com/ 没你说的问题，什么环境？

Windows10-1909，Node-v10.16.3. 使用的git最新代码

我看到别人也提到过类似的问题
https://github.com/sendya/ant-design-pro-vue/issues/322#issuecomment-509864137

**Comment by jxgahxs** [comment]
> > https://preview.pro.loacg.com/没你说的问题，什么环境？
> 
> Windows10-1909，Node-v10.16.3。使用的git最新代码
> 
> 我看到别人也提到过类似的问题
> [＃322（评论）](https://github.com/vueComponent/ant-design-vue-pro/issues/322#issuecomment-509864137)

您好，我这也遇到了与您类似的问题，首次加载时一直是在转圈。请问您是怎么解决的。

**Comment by PineSongCN** [comment]
> > > [https://preview.pro.loacg.com/没你说的问题，什么环境？](https://preview.pro.loacg.com/%E6%B2%A1%E4%BD%A0%E8%AF%B4%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E4%BB%80%E4%B9%88%E7%8E%AF%E5%A2%83%EF%BC%9F)
> > 
> > 
> > Windows10-1909，Node-v10.16.3。使用的git最新代码
> > 我看到别人也提到过类似的问题
> > [＃322（评论）](https://github.com/vueComponent/ant-design-vue-pro/issues/322#issuecomment-509864137)
> 
> 您好，我这也遇到了与您类似的问题，首次加载时一直是在转圈。请问您是怎么解决的。

凉凉，无解

**Comment by jxgahxs** [comment]
彻底没有办法了吗？线上项目。急需解决。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"清霆"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 上午9:05
收件人:&nbsp;"vueComponent/ant-design-vue-pro"<ant-design-vue-pro@noreply.github.com&gt;;
抄送:&nbsp;"胡雪松"<760115635@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue-pro] 首次进入loading的时间问题 (#611)





    
https://preview.pro.loacg.com/没你说的问题，什么环境？
  
Windows10-1909，Node-v10.16.3。使用的git最新代码
 我看到别人也提到过类似的问题
 ＃322（评论）
  
您好，我这也遇到了与您类似的问题，首次加载时一直是在转圈。请问您是怎么解决的。
  
凉凉，无解

**Comment by PineSongCN** [comment]
> 彻底没有办法了吗？线上项目。急需解决。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"清霆"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月11日(星期一) 上午9:05 收件人:&nbsp;"vueComponent/ant-design-vue-pro"<ant-design-vue-pro@noreply.github.com&gt;; 抄送:&nbsp;"胡雪松"<760115635@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [vueComponent/ant-design-vue-pro] 首次进入loading的时间问题 (#611) [https://preview.pro.loacg.com/没你说的问题，什么环境？](https://preview.pro.loacg.com/%E6%B2%A1%E4%BD%A0%E8%AF%B4%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E4%BB%80%E4%B9%88%E7%8E%AF%E5%A2%83%EF%BC%9F) Windows10-1909，Node-v10.16.3。使用的git最新代码 我看到别人也提到过类似的问题 ＃322（评论） 您好，我这也遇到了与您类似的问题，首次加载时一直是在转圈。请问您是怎么解决的。 凉凉，无解 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

试过各种，问题实在出的莫名其妙，你找找看他加载相关的代码，试试替换掉能不能解决，或者跟懒加载之类的有没有关系。

**Comment by jxgahxs** [comment]
目前已经是懒加载模式，首屏加载会有一个css特别大。是在components中。无论如何都需要1-2秒中。视觉上给的感觉是很缓慢。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"清霆"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 上午9:09
收件人:&nbsp;"vueComponent/ant-design-vue-pro"<ant-design-vue-pro@noreply.github.com&gt;;
抄送:&nbsp;"胡雪松"<760115635@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue-pro] 首次进入loading的时间问题 (#611)





  
彻底没有办法了吗？线上项目。急需解决。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"清霆"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月11日(星期一) 上午9:05 收件人:&nbsp;"vueComponent/ant-design-vue-pro"<ant-design-vue-pro@noreply.github.com&gt;; 抄送:&nbsp;"胡雪松"<760115635@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [vueComponent/ant-design-vue-pro] 首次进入loading的时间问题 (#611) https://preview.pro.loacg.com/没你说的问题，什么环境？ Windows10-1909，Node-v10.16.3。使用的git最新代码 我看到别人也提到过类似的问题 ＃322（评论） 您好，我这也遇到了与您类似的问题，首次加载时一直是在转圈。请问您是怎么解决的。 凉凉，无解 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
试过各种，问题实在出的莫名其妙，你找找看他加载相关的代码，试试替换掉能不能解决，或者跟懒加载之类的有没有关系。

**Comment by PineSongCN** [comment]
> 目前已经是懒加载模式，首屏加载会有一个css特别大。是在components中。无论如何都需要1-2秒中。视觉上给的感觉是很缓慢。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"清霆"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月11日(星期一) 上午9:09 收件人:&nbsp;"vueComponent/ant-design-vue-pro"<ant-design-vue-pro@noreply.github.com&gt;; 抄送:&nbsp;"胡雪松"<760115635@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [vueComponent/ant-design-vue-pro] 首次进入loading的时间问题 (#611) 彻底没有办法了吗？线上项目。急需解决。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"清霆"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月11日(星期一) 上午9:05 收件人:&nbsp;"vueComponent/ant-design-vue-pro"<ant-design-vue-pro@noreply.github.com&gt;; 抄送:&nbsp;"胡雪松"<760115635@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [vueComponent/ant-design-vue-pro] 首次进入loading的时间问题 (#611) [https://preview.pro.loacg.com/没你说的问题，什么环境？](https://preview.pro.loacg.com/%E6%B2%A1%E4%BD%A0%E8%AF%B4%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E4%BB%80%E4%B9%88%E7%8E%AF%E5%A2%83%EF%BC%9F) Windows10-1909，Node-v10.16.3。使用的git最新代码 我看到别人也提到过类似的问题 ＃322（评论） 您好，我这也遇到了与您类似的问题，首次加载时一直是在转圈。请问您是怎么解决的。 凉凉，无解 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 试过各种，问题实在出的莫名其妙，你找找看他加载相关的代码，试试替换掉能不能解决，或者跟懒加载之类的有没有关系。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

他默认就是懒加载吧，所以说是不是懒加载的部分有问题。

**Comment by jxgahxs** [comment]
估计有挺多的人遇到这个问题了






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"清霆"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 上午9:13
收件人:&nbsp;"vueComponent/ant-design-vue-pro"<ant-design-vue-pro@noreply.github.com&gt;;
抄送:&nbsp;"胡雪松"<760115635@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [vueComponent/ant-design-vue-pro] 首次进入loading的时间问题 (#611)





  
目前已经是懒加载模式，首屏加载会有一个css特别大。是在components中。无论如何都需要1-2秒中。视觉上给的感觉是很缓慢。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"清霆"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月11日(星期一) 上午9:09 收件人:&nbsp;"vueComponent/ant-design-vue-pro"<ant-design-vue-pro@noreply.github.com&gt;; 抄送:&nbsp;"胡雪松"<760115635@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [vueComponent/ant-design-vue-pro] 首次进入loading的时间问题 (#611) 彻底没有办法了吗？线上项目。急需解决。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"清霆"<notifications@github.com&gt;; 发送时间:&nbsp;2020年5月11日(星期一) 上午9:05 收件人:&nbsp;"vueComponent/ant-design-vue-pro"<ant-design-vue-pro@noreply.github.com&gt;; 抄送:&nbsp;"胡雪松"<760115635@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [vueComponent/ant-design-vue-pro] 首次进入loading的时间问题 (#611) https://preview.pro.loacg.com/没你说的问题，什么环境？ Windows10-1909，Node-v10.16.3。使用的git最新代码 我看到别人也提到过类似的问题 ＃322（评论） 您好，我这也遇到了与您类似的问题，首次加载时一直是在转圈。请问您是怎么解决的。 凉凉，无解 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 试过各种，问题实在出的莫名其妙，你找找看他加载相关的代码，试试替换掉能不能解决，或者跟懒加载之类的有没有关系。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
他默认就是懒加载吧，所以说是不是懒加载的部分有问题。

**Comment by yuzhewo** [comment]
同样的问题，刷新页面渲染需要五六秒左右的时间才显示。

**Comment by PineSongCN** [comment]
> 同样的问题，刷新页面渲染需要五六秒左右的时间才显示。

试试看替换vue.config.js里的CDN链接吧（不确定、未验证），我是没本事折腾ant design了。

**Comment by aimpsmile** [comment]
感觉是html整体加载完了才跳过loading.
包括网络，还要等异步数据回来，整体渲染才把loading占位内容给干掉。
